### ISSUE TITLE
Reference to temporary returned

### ISSUE THREAD

**Issue by svenvollmar** [ebertolazzi/GenericContainer#5]
Hello, we noticed that in a couple of places the objects get destroyed before they are returned.
For example here: https://github.com/ebertolazzi/GenericContainer/blob/master/src/GenericContainer.cc#L3486
`return (*_data.m_i)(i,j);`
As far as I understand this code would not work as intended.

Similar code is located here in GenericContainer.cc:
- 3496
- 3539
- 3549
- 3591
- 3601
- 3646
- 3652
- 3693

Best regards

**Comment by ebertolazzi** [comment]
In not an error. I use temporary to return a reference to a NON temporary object.
